inherit_gem:
  hint-rubocop_style:
    - default.yml

AllCops:
  TargetRubyVersion: 3.0.5
  TargetRailsVersion: 6.1
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - '**/*.haml'
    - 'config.ru'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Style/GlobalVars:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
